package com.yowyob.tiibntick.core.billing.invoice.domain.model.enums;

/**
 * Types of line items on a TiiBnTick invoice.
 *
 * <p> — Added {@link #SURCHARGE} for FreelancerOrg / DSL-generated surcharge detail lines.
 *
 * @author MANFOUO Braun
 */
public enum LineItemType {
    DELIVERY_FEE,
    EXPRESS_SURCHARGE,
    WEIGHT_SURCHARGE,
    DISTANCE_SURCHARGE,
    INSURANCE_FEE,
    PACKAGING_FEE,
    PLATFORM_FEE,
    LOYALTY_DISCOUNT,
    PROMOTIONAL_DISCOUNT,
    TAX_LINE,

    /**
     * Surcharge detail line generated by the billing DSL engine ().
     * Used when {@code Invoice.surchargeLines} need to be reflected as
     * individual line items (FRAGILE, REFRIGERATED_BOX, NIGHT, etc.).
     */
    SURCHARGE
}
