package com.yowyob.tiibntick.core.media.domain;

/**
 * Exhaustive enumeration of all media/document types managed by {@code tnt-media-core}.
 * Used across all TiiBnTick platforms: Agency, Go, Link, Point, Freelancer, Market.
 *
 * @author MANFOUO Braun
 */
public enum MediaType {

    // ── QR Codes ──────────────────────────────────────────────────────────────
    /** QR code encoding a package tracking code + HMAC signature. */
    QR_CODE,

    // ── PDF Documents ─────────────────────────────────────────────────────────
    /** Delivery manifest / bordereau de livraison (multi-package). */
    DELIVERY_MANIFEST,

    /** Invoice / facture generated by tnt-billing-invoice. */
    INVOICE_PDF,

    /** Hub deposit receipt (reçu de dépôt en point relais). */
    HUB_DEPOSIT_RECEIPT,

    /** Commission statement for a deliverer or freelancer. */
    COMMISSION_STATEMENT,

    /** Monthly operations report for an agency. */
    MONTHLY_REPORT,

    /** Hub daily activity report. */
    HUB_DAILY_REPORT,

    /** Service or logistics contract. */
    CONTRACT_PDF,

    // ── Images ────────────────────────────────────────────────────────────────
    /** Photo proof of delivery captured by deliverer. */
    DELIVERY_PROOF_PHOTO,

    /** Photo of a package taken at deposit (damage assessment). */
    PACKAGE_PHOTO,

    /** Actor profile photo (deliverer, agency operator). */
    PROFILE_PHOTO,

    // ── Signatures ────────────────────────────────────────────────────────────
    /** Digital/drawn signature captured on delivery (SVG or PNG). */
    SIGNATURE,

    // ── Identity Documents ────────────────────────────────────────────────────
    /** KYC document uploaded by a freelancer or agency for verification. */
    KYC_DOCUMENT
}
