package com.yowyob.tiibntick.core.billing.templates.domain.model;

import lombok.Builder;
import lombok.Getter;
import lombok.With;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.UUID;

/**
 * Aggregate root representing a pre-defined billing policy template in the
 * TiiBnTick catalog.
 *
 * <p>A {@code PolicyTemplate} is a complete, pre-configured billing policy
 * with sensible default values for all pricing parameters. Non-technical actors
 * can select a template and adjust only the numeric knobs (amounts, percentages,
 * thresholds) without ever writing a DSL rule.
 *
 * <p>The template catalog is seeded and maintained by the TiiBnTick platform
 * administration ({@code tnt-administration-core}). Regular actors cannot
 * create new catalog templates — they can only apply and customize existing ones,
 * or save a customized version as a personal template ({@link CustomPolicyTemplate}).
 *
 * <p><b>Template lifecycle:</b>
 * <pre>
 *   [Admin Creates Template] → ACTIVE (default)
 *          ↓
 *   [Admin Deactivates] → INACTIVE (hidden from actor catalog)
 *          ↓
 *   [Admin Re-activates] → ACTIVE
 * </pre>
 *
 * <p><b>Applicability rule:</b>
 * Each template declares the list of {@link PolicyOwnerType} values it supports.
 * The {@code TemplateApplicabilityService} uses this list to filter the catalog
 * for a given actor type.
 *
 * @author MANFOUO Braun
 * @version 1.0
 * @since 2026-05-26
 * @see TemplateParameter
 * @see CustomPolicyTemplate
 */
@Getter
@Builder
public class PolicyTemplate {

    /**
     * Internal UUID primary key. Generated by the repository on first save.
     */
    private final UUID id;

    /**
     * Business key — uniquely identifies the template across the platform.
     * Format: {@code TPL-[CATEGORY]-[VARIANT]} (e.g. {@code TPL-BASE-STD}, {@code TPL-FRAGILE}).
     * Immutable after creation.
     */
    private final String templateCode;

    /**
     * Display name of the template (English).
     * Example: "Standard Base Pricing".
     */
    private final String name;

    /**
     * Detailed description explaining the template's purpose, target actors
     * and the type of delivery scenario it covers.
     */
    private final String description;

    /**
     * Category grouping for catalog navigation.
     */
    private final TemplateCategory category;

    /**
     * Actor types that can use this template.
     * A template is only shown to actors whose type is in this list.
     */
    @Builder.Default
    private final List<PolicyOwnerType> applicableTo = new ArrayList<>();

    /**
     * Ordered list of adjustable parameters exposed to the actor for customization.
     * The actor can only modify parameter values within [minValue, maxValue] bounds.
     */
    @Builder.Default
    private final List<TemplateParameter> parameters = new ArrayList<>();

    /**
     * The default DSL rules that will be generated when this template is applied.
     * Stored as a serialized DSL string for readability and traceability.
     * The actual parsing and validation is done by {@code tnt-billing-dsl}.
     */
    private final String defaultDslRules;

    /**
     * Whether this template is currently visible and usable in the actor catalog.
     * Admin can deactivate a template to phase it out without deleting it.
     */
    @With
    private final boolean active;

    /**
     * Timestamp of template creation. Set by the repository on first save.
     */
    private final Instant createdAt;

    /**
     * Timestamp of last modification (parameter defaults update, activation state).
     */
    @With
    private final Instant updatedAt;

    // ─── Business Logic ────────────────────────────────────────────────────

    /**
     * Checks whether this template can be used by the given actor type.
     *
     * @param ownerType the actor type to check
     * @return {@code true} if the template is applicable to this actor type
     */
    public boolean isApplicableTo(PolicyOwnerType ownerType) {
        return applicableTo.contains(ownerType);
    }

    /**
     * Returns the parameter with the given key, or {@code null} if not found.
     *
     * @param key the parameter key to look up
     * @return the matching {@link TemplateParameter}, or null
     */
    public TemplateParameter findParameter(String key) {
        return parameters.stream()
                .filter(p -> p.getKey().equals(key))
                .findFirst()
                .orElse(null);
    }

    /**
     * Validates that the given custom parameter overrides are consistent with
     * this template's declared parameters (keys exist, values within bounds).
     *
     * @param customValues map of parameter key → custom value string
     * @return list of validation error messages (empty = valid)
     */
    public List<String> validateCustomValues(Map<String, String> customValues) {
        List<String> errors = new ArrayList<>();

        for (Map.Entry<String, String> entry : customValues.entrySet()) {
            String key = entry.getKey();
            String value = entry.getValue();

            TemplateParameter param = findParameter(key);
            if (param == null) {
                errors.add("Unknown parameter key: '" + key + "' for template " + templateCode);
                continue;
            }

            // Numeric bounds check for applicable types
            if (param.getType() == ParameterType.MONEY
                    || param.getType() == ParameterType.PERCENTAGE
                    || param.getType() == ParameterType.DECIMAL
                    || param.getType() == ParameterType.MULTIPLIER
                    || param.getType() == ParameterType.INTEGER) {
                try {
                    java.math.BigDecimal numericValue = new java.math.BigDecimal(value);
                    java.math.BigDecimal min = param.getMinValueAsBigDecimal();
                    java.math.BigDecimal max = param.getMaxValueAsBigDecimal();

                    if (min != null && numericValue.compareTo(min) < 0) {
                        errors.add("Parameter '" + key + "' value " + value
                                + " is below minimum " + param.getMinValue() + " " + param.getUnit());
                    }
                    if (max != null && numericValue.compareTo(max) > 0) {
                        errors.add("Parameter '" + key + "' value " + value
                                + " exceeds maximum " + param.getMaxValue() + " " + param.getUnit());
                    }
                } catch (NumberFormatException e) {
                    errors.add("Parameter '" + key + "' value '" + value
                            + "' is not a valid number for type " + param.getType());
                }
            }
        }

        return errors;
    }

    /**
     * Returns a new instance of this template with its {@code active} flag set to {@code true}.
     *
     * @return activated template
     */
    public PolicyTemplate activate() {
        return this.withActive(true).withUpdatedAt(Instant.now());
    }

    /**
     * Returns a new instance of this template with its {@code active} flag set to {@code false}.
     *
     * @return deactivated template
     */
    public PolicyTemplate deactivate() {
        return this.withActive(false).withUpdatedAt(Instant.now());
    }

    /**
     * Factory method for a new template being created by an admin.
     * Assigns a fresh UUID and sets timestamps.
     *
     * @param templateCode  business key (e.g. TPL-BASE-STD)
     * @param name          display name
     * @param description   long description
     * @param category      template category
     * @param applicableTo  list of applicable owner types
     * @param parameters    list of adjustable parameters
     * @param defaultDslRules default DSL string
     * @return new active PolicyTemplate instance
     */
    public static PolicyTemplate createNew(
            String templateCode,
            String name,
            String description,
            TemplateCategory category,
            List<PolicyOwnerType> applicableTo,
            List<TemplateParameter> parameters,
            String defaultDslRules) {

        Instant now = Instant.now();
        return PolicyTemplate.builder()
                .id(UUID.randomUUID())
                .templateCode(templateCode)
                .name(name)
                .description(description)
                .category(category)
                .applicableTo(new ArrayList<>(applicableTo))
                .parameters(new ArrayList<>(parameters))
                .defaultDslRules(defaultDslRules)
                .active(true)
                .createdAt(now)
                .updatedAt(now)
                .build();
    }
}
