-- ============================================================
-- TiiBnTick Core — tnt-billing-templates
-- Migration: 001_create_billing_policy_templates
--
-- Creates the main catalog table for billing policy templates.
-- Each template represents a pre-defined billing policy configuration
-- that can be applied by service actors (Agency, FreelancerOrg, Point, Link).
--
-- Author  : MANFOUO Braun
-- Module  : tnt-billing-templates (L5 Billing Engine)
-- Version : 0.0.1
-- Date    : 2026-05-26
-- ============================================================

-- liquibase formatted sql

-- changeset manfouo-braun:001-billing-policy-templates
-- comment: Creates billing_policy_templates catalog table

CREATE TABLE IF NOT EXISTS billing_policy_templates (
    -- Primary key: UUID generated by the application
    id                  UUID            NOT NULL,

    -- Business key: unique template code (e.g. TPL-BASE-STD, TPL-FRAGILE)
    template_code       VARCHAR(100)    NOT NULL,

    -- Display name shown in the UI
    name                VARCHAR(255)    NOT NULL,

    -- Long description of the template purpose and target scenario
    description         TEXT,

    -- Category for catalog grouping
    -- Values: BASE | SPECIALTY | LOYALTY | TIME | WEATHER | HUB | NETWORK | COMMISSION | MARKETPLACE
    category            VARCHAR(50)     NOT NULL,

    -- JSON array of applicable owner type strings
    -- Example: ["AGENCY","FREELANCER_ORG"]
    -- Filtering in application layer for JSON compatibility across databases
    applicable_to_json  TEXT            NOT NULL DEFAULT '[]',

    -- Default DSL rule string generated when template is applied with default params
    -- Stored for documentation, audit, and fallback in DslRuleGeneratorService
    default_dsl_rules   TEXT,

    -- Whether the template is visible and usable by actors in the catalog
    is_active           BOOLEAN         NOT NULL DEFAULT TRUE,

    -- Timestamps
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_billing_policy_templates PRIMARY KEY (id),
    CONSTRAINT uq_billing_policy_templates_code UNIQUE (template_code)
);

-- Index for active template lookup (most common query)
CREATE INDEX IF NOT EXISTS idx_billing_policy_templates_active
    ON billing_policy_templates (is_active);

-- Index for category-based browsing
CREATE INDEX IF NOT EXISTS idx_billing_policy_templates_category
    ON billing_policy_templates (category);

-- Index for direct code lookup
CREATE INDEX IF NOT EXISTS idx_billing_policy_templates_code
    ON billing_policy_templates (template_code);

-- rollback DROP TABLE IF EXISTS billing_policy_templates;
