-- ============================================================
-- TiiBnTick Core — tnt-billing-templates
-- Migration: 004_create_billing_custom_policy_templates
--
-- Stores personalized template snapshots saved by service actors
-- for future reuse. These are private to each actor and are not
-- visible in the global template catalog.
--
-- Author  : MANFOUO Braun
-- Module  : tnt-billing-templates (L5 Billing Engine)
-- Version : 0.0.1
-- Date    : 2026-05-26
-- ============================================================

-- liquibase formatted sql

-- changeset manfouo-braun:004-billing-custom-policy-templates
-- comment: Creates billing_custom_policy_templates table for actor-owned custom templates

CREATE TABLE IF NOT EXISTS billing_custom_policy_templates (
    -- Primary key: UUID generated by the application
    id                              UUID            NOT NULL,

    -- The actor UUID who owns this custom template
    -- References kernel actorId — no FK to avoid cross-module coupling
    owner_actor_id                  VARCHAR(255)    NOT NULL,

    -- The actor type (enum name): AGENCY | FREELANCER_ORG | POINT | LINK | ADMIN | MARKET
    owner_type                      VARCHAR(50)     NOT NULL,

    -- User-defined display name for this custom template
    -- Example: "Mon tarif habituel Yaoundé", "Ernest Pharma Standard Rate"
    name                            VARCHAR(255)    NOT NULL,

    -- Source catalog template code (nullable if created from scratch by admin)
    -- Example: TPL-BASE-STD, TPL-FRAGILE
    source_template_code            VARCHAR(100),

    -- UUID of the last BillingPolicy generated from this custom template (nullable)
    -- Updated each time the actor re-applies this template
    last_generated_policy_id        UUID,

    -- JSON-serialized map of parameter key → custom value string
    -- Example: {"basePrice":"700","perKmRate":"60","fragile_surcharge_pct":"25"}
    customized_parameters_json      TEXT            NOT NULL DEFAULT '{}',

    -- Timestamps
    created_at                      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at                      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_billing_custom_policy_templates PRIMARY KEY (id)
);

-- Index for actor-specific retrieval
CREATE INDEX IF NOT EXISTS idx_billing_custom_templates_owner
    ON billing_custom_policy_templates (owner_actor_id);

-- Index for source template analytics (how many actors customized a given template)
CREATE INDEX IF NOT EXISTS idx_billing_custom_templates_source
    ON billing_custom_policy_templates (source_template_code);

-- rollback DROP TABLE IF EXISTS billing_custom_policy_templates;
