CREATE TABLE IF NOT EXISTS relay_deposits (
    id UUID PRIMARY KEY,
    packet_id UUID NOT NULL REFERENCES packets(id) ON DELETE CASCADE,
    client_id UUID NOT NULL REFERENCES persons(id) ON DELETE CASCADE,
    logistics_id UUID NOT NULL REFERENCES logistics(id) ON DELETE CASCADE,
    storage_fee DOUBLE PRECISION NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    retrieved_at TIMESTAMP WITH TIME ZONE
);
