package com.yowyob.tiibntick.core.billing.invoice.application.port.in.command;

import com.yowyob.tiibntick.core.billing.invoice.domain.model.InvoiceDiscount;
import com.yowyob.tiibntick.core.billing.invoice.domain.model.InvoiceLine;
import com.yowyob.tiibntick.core.billing.invoice.domain.model.SurchargeLineItem;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;

import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

/**
 * Command to generate a new invoice for a delivery mission or sales order.
 *
 * <p> — Added FreelancerOrg issuer context fields and template metadata.
 *
 * @author MANFOUO Braun
 */
public record GenerateInvoiceCommand(
        @NotNull UUID tenantId,
        @NotBlank String tenantCode,
        @NotBlank String countryCode,
        String missionId,
        String salesOrderId,
        @NotBlank String clientId,
        @NotEmpty List<InvoiceLine> lines,
        List<InvoiceDiscount> discounts,
        @NotBlank String currency,
        LocalDateTime dueAt,

        // ── : FreelancerOrg issuer context ─────────────────────────────

        /**
         * Type of the org issuing this invoice.
         * Values: AGENCY | FREELANCER_ORG | POINT | LINK
         * Null = standard platform invoice.
         */
        String issuerOrgType,

        /**
         * UUID of the issuing org (FreelancerOrg or Agency).
         * References tnt-organization-core UUID — pure integration key.
         */
        String issuerOrgId,

        /**
         * Trade name to display on the invoice header.
         * For FreelancerOrg: their registered trade name.
         */
        String issuerTradeName,

        /**
         * Whether TVA/VAT is applicable (based on issuer registration status).
         */
        Boolean vatApplicable,

        /**
         * Surcharge detail lines generated by the billing DSL engine.
         * Displayed on the PDF for client transparency.
         */
        List<SurchargeLineItem> surchargeLines,

        /**
         * Whether this invoice was generated from a billing policy template.
         */
        Boolean isFromTemplate,

        /**
         * Name of the applied billing policy template (e.g. "TPL-FRAGILE").
         */
        String appliedTemplateName
) {
    public GenerateInvoiceCommand {
        if (missionId == null && salesOrderId == null) {
            throw new IllegalArgumentException("Either missionId or salesOrderId must be provided");
        }
        if (discounts == null) discounts = List.of();
        if (surchargeLines == null) surchargeLines = List.of();
        if (dueAt == null) dueAt = LocalDateTime.now().plusDays(7);
    }

    /**
     * Backward-compatible constructor without  fields.
     */
    public static GenerateInvoiceCommand simple(
            UUID tenantId, String tenantCode, String countryCode,
            String missionId, String salesOrderId, String clientId,
            List<InvoiceLine> lines, List<InvoiceDiscount> discounts,
            String currency, LocalDateTime dueAt) {
        return new GenerateInvoiceCommand(tenantId, tenantCode, countryCode,
                missionId, salesOrderId, clientId, lines, discounts, currency, dueAt,
                null, null, null, null, List.of(), null, null);
    }
}
