package com.yowyob.tiibntick.core.billing.invoice.adapter.in.web.dto.request;

import com.yowyob.tiibntick.core.billing.invoice.domain.model.InvoiceDiscount;
import com.yowyob.tiibntick.core.billing.invoice.domain.model.InvoiceLine;
import com.yowyob.tiibntick.core.billing.invoice.domain.model.SurchargeLineItem;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotEmpty;

import java.time.LocalDateTime;
import java.util.List;

/**
 * HTTP request body for invoice generation.
 *
 * <p> — Added FreelancerOrg issuer context and template metadata fields.
 *
 * @author MANFOUO Braun
 */
public record GenerateInvoiceRequest(
        @NotBlank String tenantCode,
        @NotBlank String countryCode,
        String missionId,
        String salesOrderId,
        @NotBlank String clientId,
        @NotEmpty List<InvoiceLine> lines,
        List<InvoiceDiscount> discounts,
        @NotBlank String currency,
        LocalDateTime dueAt,

        // : FreelancerOrg issuer context
        @Schema(description = "Type of the org issuing this invoice: AGENCY | FREELANCER_ORG | POINT | LINK",
                example = "FREELANCER_ORG")
        String issuerOrgType,

        @Schema(description = "UUID of the issuing org (FreelancerOrg or Agency)",
                example = "550e8400-e29b-41d4-a716-446655440000")
        String issuerOrgId,

        @Schema(description = "Trade name displayed on the invoice header",
                example = "Moto Express Biyem")
        String issuerTradeName,

        @Schema(description = "Whether TVA/VAT is applicable for this invoice",
                example = "false")
        Boolean vatApplicable,

        @Schema(description = "Surcharge detail lines generated by the billing DSL")
        List<SurchargeLineItem> surchargeLines,

        @Schema(description = "Whether this invoice was generated from a billing policy template",
                example = "true")
        Boolean isFromTemplate,

        @Schema(description = "Name of the applied billing policy template",
                example = "TPL-FRAGILE")
        String appliedTemplateName
) {}
